global using System.Threading.Tasks;
global using GestioneSagre.Core.Models.Entities;
global using GestioneSagre.Mapper;
global using GestioneSagre.Tools.Enums;
global using GestioneSagre.Tools.ValueObjects;
global using ImageMagick;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.Http;
global using Microsoft.EntityFrameworkCore;
